version: '3'
services:
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80

  mysql:
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/sql:/docker-entrypoint-initdb.d
    env_file:
    - ./mysql/.env
    ports:
      - 13306:3306

  elasticsearch:
    image: elasticsearch:7.9.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  redis:
    image: redis:6
    ports:
      - 6379:6379
volumes:
  mysql:
